export const userData = [
    {
        id: 1,
        username: 'admin',
        email: 'admin',
        password: 'admin',
        role: 'admin',
        createdAt: '2021-01-01',
        updatedAt: '2021-01-01',
    },
    {
        id: 2,
        username: 'admin',
        email: 'admin2@example.com',
        password: 'admin1234',
        role: 'admin',
        createdAt: '2021-01-01',
        updatedAt: '2021-01-01',
    },
    {
        id: 3,
        username: 'admin',
        email: 'admin@example.com',
        password: 'admin123',
        role: 'user',
        createdAt: '2021-01-01',
        updatedAt: '2021-01-01',
    },
    {
        id: 4,
        username: 'user12',
        email: 'user12@gmail.com',
        password: 'user12',
        role: 'user',
        createdAt: '2021-01-01',
        updatedAt: '2021-01-01',
    },
    {
        id: 5,
        username: 'user5',
        email: 'user5@example.com',
        password: 'user5',
        role: 'user',
        createdAt: '2021-01-01',
        updatedAt: '2021-01-01',
    },
    {
        id: 6,
        username: 'user',
        email: 'user',
        password: 'user',
        role: 'user',
        createdAt: '2021-01-01',
        updatedAt: '2021-01-01',
    },
];
